### ISSUE TITLE
Update the Readme.md file.

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/Project-Template-Hacktoberfest22#1]
Create a readme sample file that can be used as a template for the hacktoberfest 2022 projects.
Clearly mention the places where users need to make changes.

**Comment by Soumyajit2825** [comment]
@chaitak-gorai can u assign me to do it?

**Comment by chaitak-gorai** [comment]
Hello Soumyajit, thank you for your interest. Actually, we are hosting a hacktoberfest event in our college. So this template will be prepared for that event only by our speakers to demonstrate to the beginners. So sorry we can't assign this to you as of now.
But feel free to use this template for your upcoming hacktoberfest projects.

**Comment by Soumyajit2825** [comment]
ok ok
